### PR TITLE
Add support for Stargaze

### PR DESCRIPTION
**Pull request by 4coffeeihadbreakfast**
* begin adding support for stargaze
* missing some values
* no channel-10 asset enabled on secret, so i don't think this can be added yet.
* untested

### CODE REVIEW

**Comment by assafmo** [comment]
Hi, thanks! Can you confirm there are at least 2 relayers on that connection? We require it because 1 relayer is usually not enough to provide a good QoS.

**Comment by 4coffeeihadbreakfast** [comment]
Hi @assafmo I'm a newb so not sure i'm doing this right but I assume that means I need to check the channels from secret to stargaze. e.g. channel-10 and channel-18 and see how many "Relayer Operator" there are? If that is the case I only see 1 => https://www.mintscan.io/secret/relayers/channel-10

**Comment by assafmo** [comment]
Yes, this makes it unreliable...

**Comment by jlm0** [comment]
Stargaze does have CryptoCrew and StakeLab relaying. The details were added in the new wrap PR. So this can probably be closed without merge.

**Pull request closed without merging**
