### PR TITLE
Added responsive UI

### PR DESCRIPTION
**Pull request by calvinkei**
Some users would like to use wrap.scrt.network on Fina but it is currently not possible due to the lack of responsive UI. I have made some quick changes to make it at least useable on mobile. Here is a preview:

https://user-images.githubusercontent.com/14106911/188327271-63adefa5-6e68-46e2-900c-3c82b175ef37.MP4

### CODE REVIEW

**Comment by assafmo** [comment]
Amazing!!!

**Comment by assafmo** [comment]
Wanted to do this, thank you!

**Comment by assafmo** [comment]
Will test it out and merge, hopefully this week.

**Comment by calvinkei** [comment]
thank you🙏

**Pull request merged**
